version: 2.1
workflows:
  test1:
    jobs:
      - build
#      - sync:
#          requires:
#            - build
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: python --version
      - run: pip install pytest
      - run:
          name: run test
          command: pytest --version
#  sync:
#    docker:
#      - image: rclone/rclone