version: 2.1
workflows:
  test1:
    jobs:
      - build
      - test:
          requires:
            - build
#      - sync:
#          requires:
#            - test
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run:
          name: run main1
          command: python main1.py locales/en1.yml > my_workspace/out.json
      - persist_to_workspace:
        root: my_workspace
        paths:
          - out.json
  test:
    working_directory: ~/test
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: python test1.py
      - attach_workspace:
        at: my_workspace
      - run: diff locales/en2.json out.json
#  sync:
#    docker:
#      - image: rclone/rclone