version: 2.1
workflows:
  test1:
    jobs:
      - build
#      - sync:
#          requires:
#            - build
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: run test
#         command: python --version
          command: pytest --version
#  sync:
#    docker:
#      - image: rclone/rclone